sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
addons:
  apt:
    packages:
      - libgmp-dev

env:
  - USE_MINI_PORTILE=true
  - USE_MINI_PORTILE=false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.0
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - env: USE_MINI_PORTILE=false
